-- Tabla de permisos predeterminados por rol
-- Permite administrar los permisos base de cada rol desde el Mantenedor de Roles.
-- La herencia funciona así: permisos_usuario (overrides) se fusionan sobre permisos_rol (base).

CREATE TABLE IF NOT EXISTS permisos_rol (
  rol           TEXT        PRIMARY KEY,
  permisos      JSONB       NOT NULL DEFAULT '{}',
  descripcion   TEXT        NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger para mantener updated_at al día
CREATE OR REPLACE FUNCTION set_permisos_rol_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_permisos_rol_updated_at
  BEFORE UPDATE ON permisos_rol
  FOR EACH ROW EXECUTE FUNCTION set_permisos_rol_updated_at();

-- RLS
ALTER TABLE permisos_rol ENABLE ROW LEVEL SECURITY;

-- Lectura: cualquier usuario autenticado puede leer
CREATE POLICY "permisos_rol_select"
  ON permisos_rol FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Escritura: solo admin
CREATE POLICY "permisos_rol_insert"
  ON permisos_rol FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND rol = 'admin')
  );

CREATE POLICY "permisos_rol_update"
  ON permisos_rol FOR UPDATE
  USING (
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND rol = 'admin')
  );

CREATE POLICY "permisos_rol_delete"
  ON permisos_rol FOR DELETE
  USING (
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND rol = 'admin')
  );

-- ─── Datos iniciales ────────────────────────────────────────────────────────
-- Refleja exactamente PERMISOS_POR_ROL definido en src/pages/Usuarios.jsx

INSERT INTO permisos_rol (rol, permisos, descripcion) VALUES

('directivo', '{
  "ver_inventario": true,
  "agregar_bien": true,
  "editar_bien": true,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": true,
  "exportar": true,
  "registrar_prestamo": true,
  "registrar_incidencia": true,
  "ver_auditoria_inventario": true,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": false,
  "crear_ticket": false,
  "editar_ticket": false,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": false,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": false,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": false,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": false,
  "gestionar_campos": false,
  "ver_ajustes": false,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": false,
  "gestionar_roles": false
}', 'Acceso al inventario institucional y sus auditorías.'),

('coordinador', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": true,
  "editar_ticket": true,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": true,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": true,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": true,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": true,
  "gestionar_campos": false,
  "ver_ajustes": true,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": true,
  "gestionar_roles": false
}', 'Acceso a tickets, sus propias ausencias y ajustes básicos.'),

('docente', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": true,
  "editar_ticket": true,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": true,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": true,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": true,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": true,
  "gestionar_campos": false,
  "ver_ajustes": true,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": true,
  "gestionar_roles": false
}', 'Acceso a tickets, sus propias ausencias y ajustes básicos.'),

('asistente', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": true,
  "editar_ticket": true,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": true,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": true,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": true,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": true,
  "gestionar_campos": false,
  "ver_ajustes": true,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": true,
  "gestionar_roles": false
}', 'Asistente de la educación con acceso a tickets y sus propias ausencias.'),

('administrativo', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": true,
  "editar_ticket": true,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": true,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": true,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": true,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": true,
  "gestionar_campos": false,
  "ver_ajustes": true,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": true,
  "gestionar_roles": false
}', 'Personal administrativo con acceso a tickets y sus propias ausencias.'),

('soporte', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": true,
  "editar_ticket": true,
  "gestionar_tickets": true,
  "eliminar_ticket": true,
  "ver_alertas_tickets": true,
  "exportar_tickets": true,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": true,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": true,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": true,
  "gestionar_campos": false,
  "ver_ajustes": true,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": true,
  "gestionar_roles": false
}', 'Soporte técnico con acceso completo a tickets.'),

('visor_requerimientos', '{
  "ver_inventario": false,
  "agregar_bien": false,
  "editar_bien": false,
  "eliminar_bien": false,
  "eliminar_lote": false,
  "gestionar_categorias": false,
  "importar_csv": false,
  "exportar": false,
  "registrar_prestamo": false,
  "registrar_incidencia": false,
  "ver_auditoria_inventario": false,
  "ver_campos": false,
  "agregar_campo": false,
  "editar_campo": false,
  "ocultar_campo": false,
  "eliminar_campo": false,
  "reordenar_campos": false,
  "gestionar_campos_base": false,
  "ver_tickets": true,
  "crear_ticket": false,
  "editar_ticket": false,
  "gestionar_tickets": false,
  "eliminar_ticket": false,
  "ver_alertas_tickets": false,
  "exportar_tickets": false,
  "ver_requerimientos": false,
  "crear_requerimiento": false,
  "editar_requerimiento": false,
  "eliminar_requerimiento": false,
  "importar_requerimientos": false,
  "exportar_requerimientos": false,
  "ver_auditoria_requerimientos": false,
  "ver_propias_ausencias": false,
  "ver_ausencias": false,
  "crear_ausencias": false,
  "editar_ausencias": false,
  "eliminar_ausencias": false,
  "aprobar_ausencias": false,
  "exportar_ausencias": false,
  "ver_auditoria_permisos": false,
  "invitar_usuario": false,
  "editar_usuario": false,
  "eliminar_usuario": false,
  "notificar_ausencia_correo": false,
  "ver_compensatorios": false,
  "crear_compensatorios": false,
  "editar_compensatorios": false,
  "eliminar_compensatorios": false,
  "exportar_compensatorios": false,
  "ver_auditoria_compensatorios": false,
  "gestionar_ajustes": false,
  "gestionar_campos": false,
  "ver_ajustes": false,
  "gestionar_usuarios": false,
  "editar_roles_permisos": false,
  "guardar_cambios_ajustes": false,
  "gestionar_roles": false
}', 'Solo puede ver tickets propios.')

ON CONFLICT (rol) DO NOTHING;
